version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "shop"
    volumes:
      - ./dump/dbexport.sql:/docker-entrypoint-initdb.d/dbexport.sql
    ports:
      - "5001:5432"
  
volumes:
  postgres-data: