version: "3.9"
services:

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "shop"
    volumes:
      - ./dump/dbexport.sql:/docker-entrypoint-initdb.d/dbexport.sql
    ports:
      - "5001:5432"

  server:
    build: server/
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - USERTEST=postgresql://postgres:postgres@db:5432/shop
    ports:
      - 8000:8000